//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColumnDepence.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColumnDepence.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap CloseImage {
            get {
                object obj = ResourceManager.GetObject("CloseImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FilterByColumn {
            get {
                object obj = ResourceManager.GetObject("FilterByColumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LoadAllValues {
            get {
                object obj = ResourceManager.GetObject("LoadAllValues", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LoadDefinitionImage {
            get {
                object obj = ResourceManager.GetObject("LoadDefinitionImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon programIcon {
            get {
                object obj = ResourceManager.GetObject("programIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT    COL1.name AS Referenced_Column , COL2.name AS Parent_Column ,tb2.name AS TableName 
        ///FROM  sys.columns AS COL1 INNER JOIN
        ///                      sys.columns AS COL2 INNER JOIN
        ///                      sys.tables AS tb2 INNER JOIN
        ///                      sys.foreign_key_columns AS FK INNER JOIN
        ///                      sys.tables AS tb ON FK.parent_object_id = tb.object_id ON tb2.object_id = FK.referenced_object_id ON COL2.column_id = FK.referenced_column_id AND
        ///                       COL2.object_id =  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SqlChildReferences {
            get {
                return ResourceManager.GetString("SqlChildReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select CN.COLUMN_NAME As [Column] ,TB.CONSTRAINT_NAME as [Constraint] , TB.CONSTRAINT_TYPE as [Type] 
        /// from  INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CN inner join 
        ///  INFORMATION_SCHEMA.TABLE_CONSTRAINTS TB on (CN.TABLE_NAME = TB.TABLE_NAME AND CN.CONSTRAINT_NAME = TB.CONSTRAINT_NAME) 
        /// WHERE  CN.TABLE_NAME = @TABSEARCH.
        /// </summary>
        public static string SqlColumnConstrains {
            get {
                return ResourceManager.GetString("SqlColumnConstrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COL2.name AS Parent_Column , COL1.name AS Referenced_Column , tb.name AS TableName 
        /// FROM sys.columns AS COL1 INNER JOIN
        ///                      sys.columns AS COL2 INNER JOIN
        ///                      sys.tables AS tb2 INNER JOIN
        ///                      sys.foreign_key_columns AS FK INNER JOIN
        ///                      sys.tables AS tb ON FK.parent_object_id = tb.object_id ON tb2.object_id = FK.referenced_object_id ON COL2.column_id = FK.referenced_column_id AND
        ///                       COL2.object_id = FK. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SqlParentReferenes {
            get {
                return ResourceManager.GetString("SqlParentReferenes", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ToolBoxImage {
            get {
                object obj = ResourceManager.GetObject("ToolBoxImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
